version: "3.3"
services:
  nginx:
    image: "nginx:1.17"
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - "80:80"
  frontend:
    build: "../../1/1.10/"
  backend:
    build: "../../1/1.11/"
    environment:
      REDIS: "redis"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "s3cretDatabase"
      DB_HOST: "postgres"
  redis:
    image: "redis:5"
  postgres:
    image: "postgres:12"
    volumes:
    - "./database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "s3cretDatabase"
